### PR TITLE
further distill matrix, following @camptocamp's example

### PR DESCRIPTION
**Pull request by igalic**
an attempt at fixing #10

### CODE REVIEW

**Comment by igalic** [comment]
let's see what travis thinks of this.

we also still need to fix our rspec issue

**Comment by igalic** [comment]
well, this looks fine, but i have no idea which puppet version we're testing :s

**Comment by igalic** [comment]
oh! i have to uncollapse bundle install to see.
we're testing puppet 3.6.2 (for facter 1.7.x), and puppet 3.7.4 (latest) for the others.

@daenney do you think that's "enough"?

**Comment by nibalizer** [comment]
lgtm

**Comment by igalic** [comment]
next up, fixing 1.8.7 builds, and as soon as that's done, we can release again

**Pull request merged**
