### PR TITLE
test more puppet versions

### PR DESCRIPTION
**Pull request by igalic**
test for strict-variables and future parser compatibility

### CODE REVIEW

**Comment by nibalizer** [comment]
3.5 was only released for like 2 weeks ( and was terrible) also while you're here why not remove the 2.7

**Comment by igalic** [comment]
okay

**Comment by igalic** [comment]
@nibalizer looks gooder now, but travis isn't picking this repository up, actually :(

**Comment by igalic** [comment]
squash/force push to make travis pick it up

**Comment by igalic** [comment]
i'm counting a 1.8.7 failure to due puppet-rspec fuckup as a success.

**Comment by igalic** [comment]
*hits merge button*

**Pull request merged**
